CREATE DATABASE CONSTRUTORA;

GO

USE CONSTRUTORA;

GO

CREATE TABLE DEPARTAMENTO(
	CODIGO INT NOT NULL IDENTITY,
	NOME VARCHAR(30),
	CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(CODIGO),
);

GO

CREATE TABLE FUNCIONARIO (
	CODIGO INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	CPF CHAR(11) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	COD_DEPARTAMENTO INT NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	DATA_HORA_CADASTRO DATETIME NOT NULL DEFAULT GETDATE(),
	ATIVO BIT NOT NULL DEFAULT 1,

	CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(CODIGO),
	CONSTRAINT UQ_FUNCIONARIO_EMAIL UNIQUE(EMAIL),
	CONSTRAINT UQ_FUNCIONARIO_CPF UNIQUE(CPF),
	CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO FOREIGN KEY(COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(CODIGO),
);

GO

CREATE TABLE PROJETO(
	CODIGO INT NOT NULL IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_TERMINO DATE NULL,
	COD_FUNCIONARIO_GERENTE INT NOT NULL,

	CONSTRAINT PK_PROJETO PRIMARY KEY(CODIGO),
	CONSTRAINT FK_PROJETO_FUNCIONARIO FOREIGN KEY(COD_FUNCIONARIO_GERENTE) REFERENCES FUNCIONARIO(CODIGO),
	CONSTRAINT CK_PROJETO_DATA_TERMINO CHECK(DATA_TERMINO IS NULL OR DATA_TERMINO>=DATA_INICIO),
);

GO

CREATE TABLE FUNCIONARIO_PROJETO (
	CODIGO INT NOT NULL IDENTITY,
	COD_FUNCIONARIO INT NOT NULL,
	COD_PROJETO INT NOT NULL,
	DATA_ENTRADA DATE NOT NULL,
	DATA_SAIDA DATE NULL,
	HRS_TRABALHADAS REAL NOT NULL,
	
	CONSTRAINT PK_FUNCIONARIO_PROJETO PRIMARY KEY(CODIGO),
	CONSTRAINT FK_FUNCIONARIO_PROJETO_FUNCIONARIO FOREIGN KEY (COD_FUNCIONARIO) REFERENCES FUNCIONARIO(CODIGO),
	CONSTRAINT FK_FUNCIONARIO_PROJETO FOREIGN KEY(COD_PROJETO) REFERENCES PROJETO(CODIGO),
	CONSTRAINT CK_FUNCIONARIO_PROJETO_DATA_SAIDA CHECK(DATA_SAIDA IS NULL OR DATA_SAIDA>=DATA_ENTRADA),
);
